server:
  port: 8080 
  address: 0.0.0.0 # To make it accessible from outside the container


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem
          expiration: 604800000   # to set the expiration time for the JWT about 7 days (in milliseconds)

  application:
    name: auth-service

  services:
    profile-service:
      name: user-service
      url: http://${spring.services.profile-service.name}/users/profile/

  cloud:
    consul:
      host: consul # The name of the Consul service in Docker Compose
      port: 8500
      discovery:
        hostname: auth-service 
        port: ${server.port}
        register: true
        health-check-path: /health
        health-check-interval: 10s
        service-name: auth-service
        instance-id: ${spring.application.name}-${random.value}

