server:
  port: 8080


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem
          expiration: 604800000   # to set the expiration time for the JWT about 7 days (in milliseconds)


