version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: oumeri
      MONGO_INITDB_ROOT_PASSWORD: PantryScanner2024
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: oumeri
      ME_CONFIG_MONGODB_ADMINPASSWORD: PantryScanner2024 
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_SITE_ADMINUSERNAME: admin 
      ME_CONFIG_SITE_ADMINPASSWORD: admin
    depends_on:
      - mongo
    networks:
      - shared-network

  user-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://oumeri:PantryScanner2024@mongo-user:27017/User-Service?authSource=admin
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      USER_QUEUE: user.index
      PORT: 5001
    depends_on:
      - mongo
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  mongo_data:
    driver: local
