version: "3.8"

services:

  kong:
    image: kong:3.5
    environment:
      KONG_DATABASE: "off" # Use DB-less mode
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"   # public gateway
      - "8001:8001"   # admin API
    volumes:
      - ./Kong/kong.yml:/kong/kong.yml
      - ./Kong/kong.conf:/etc/kong/kong.conf

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"     # Web UI, HTTP API
      - "8600:8600/udp" # DNS


networks:
  default:
    driver: bridge
