server:
port: 5004
address: 0.0.0.0

spring:
application:
  name: contact-service

rabbitmq:
  contact-queue: contact.index

cloud:
  consul:
    host: consul
    port: 8500
    discovery:
      hostname: contact-service
      port: ${server.port}
      register: true
      health-check-path: /health
      health-check-interval: 10s
      service-name: contact-service
      instance-id: "${spring.application.name}-${random.value}"