server:
  port: 5003
  # address: 0.0.0.0


spring:
  application:
    name: interview-service

  rabbitmq:
    interview-queue: interview.index

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 192.168.1.12 #host.docker.internal
        port: ${server.port}
        register: true
        health-check-path: /health
        health-check-interval: 10s
        service-name: interview-service
        instance-id: ${spring.application.name}-${random.value}

