version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-contact
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: oumeri
      MONGO_INITDB_ROOT_PASSWORD: PantryScanner2024
    volumes:
      - mongo_data_contact:/data/db
    networks:
      - jbt-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
  
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express-contact
    restart: unless-stopped
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: oumeri
      ME_CONFIG_MONGODB_ADMINPASSWORD: PantryScanner2024 
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - jbt-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - jbt-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  contact-service:
    build: .
    ports:
      - "5004:5004"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://oumeri:PantryScanner2024@mongo:27017/ContactService?authSource=admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_CLOUD_CONSUL_ENABLED: "false" # To disable Consul for dev
    restart: unless-stopped
    networks:
      - jbt-network

networks:
  jbt-network:
    external: true

volumes:
  mongo_data_contact:  # Define the named volume
    driver: local
